//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolInformationManagementSystemDBEntities : DbContext
    {
        public SchoolInformationManagementSystemDBEntities()
            : base("name=SchoolInformationManagementSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAcademicQuarter> tblAcademicQuarters { get; set; }
        public virtual DbSet<tblCalendar> tblCalendars { get; set; }
        public virtual DbSet<tblCampu> tblCampus { get; set; }
        public virtual DbSet<tblCaseType> tblCaseTypes { get; set; }
        public virtual DbSet<tblCourse> tblCourses { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmergencyContact> tblEmergencyContacts { get; set; }
        public virtual DbSet<tblEvaluationCriteria> tblEvaluationCriterias { get; set; }
        public virtual DbSet<tblExamType> tblExamTypes { get; set; }
        public virtual DbSet<tblExtraCurricularActivity> tblExtraCurricularActivities { get; set; }
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblGrade> tblGrades { get; set; }
        public virtual DbSet<tblGradeCourse> tblGradeCourses { get; set; }
        public virtual DbSet<tblGradeSection> tblGradeSections { get; set; }
        public virtual DbSet<tblMaritalStatu> tblMaritalStatus { get; set; }
        public virtual DbSet<tblMeetingFollowup> tblMeetingFollowups { get; set; }
        public virtual DbSet<tblMeetingSchedule> tblMeetingSchedules { get; set; }
        public virtual DbSet<tblMeetingType> tblMeetingTypes { get; set; }
        public virtual DbSet<tblPaymentPeriod> tblPaymentPeriods { get; set; }
        public virtual DbSet<tblPaymentReason> tblPaymentReasons { get; set; }
        public virtual DbSet<tblPenalityType> tblPenalityTypes { get; set; }
        public virtual DbSet<tblPermissionType> tblPermissionTypes { get; set; }
        public virtual DbSet<tblRegion> tblRegions { get; set; }
        public virtual DbSet<tblRelationshipType> tblRelationshipTypes { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblStudentAdmission> tblStudentAdmissions { get; set; }
        public virtual DbSet<tblStudentAttendance> tblStudentAttendances { get; set; }
        public virtual DbSet<tblStudentDiscipline> tblStudentDisciplines { get; set; }
        public virtual DbSet<tblStudentMark> tblStudentMarks { get; set; }
        public virtual DbSet<tblStudentPayment> tblStudentPayments { get; set; }
        public virtual DbSet<tblStudentTutorial> tblStudentTutorials { get; set; }
        public virtual DbSet<tblSubCity> tblSubCities { get; set; }
        public virtual DbSet<tblTeacher> tblTeachers { get; set; }
        public virtual DbSet<tblTeacherEvaluation> tblTeacherEvaluations { get; set; }
        public virtual DbSet<tblTeachersAttendance> tblTeachersAttendances { get; set; }
        public virtual DbSet<tblTeacherTutorial> tblTeacherTutorials { get; set; }
        public virtual DbSet<tblWoreda> tblWoredas { get; set; }
    }
}
