//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public int ID { get; set; }
        public string SchoolName { get; set; }
        public byte[] SchoolLogo { get; set; }
        public System.DateTime PaymentStartingDate { get; set; }
        public System.DateTime PaymentEndingDate { get; set; }
        public int PassingMark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
