//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent()
        {
            this.tblStudentAdmissions = new HashSet<tblStudentAdmission>();
            this.tblStudentAttendances = new HashSet<tblStudentAttendance>();
            this.tblStudentDisciplines = new HashSet<tblStudentDiscipline>();
            this.tblStudentMarks = new HashSet<tblStudentMark>();
            this.tblStudentPayments = new HashSet<tblStudentPayment>();
            this.tblStudentTutorials = new HashSet<tblStudentTutorial>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public string MotherName { get; set; }
        public int GenderID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int CampusID { get; set; }
        public int GradeSectionID { get; set; }
        public int RegionID { get; set; }
        public int SubCityID { get; set; }
        public int WoredaID { get; set; }
        public string HouseNo { get; set; }
        public bool IsSponsored { get; set; }
        public bool IsHandicaped { get; set; }
        public int AdmissionYear { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblCampu tblCampu { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblGradeSection tblGradeSection { get; set; }
        public virtual tblRegion tblRegion { get; set; }
        public virtual tblSubCity tblSubCity { get; set; }
        public virtual tblWoreda tblWoreda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentAdmission> tblStudentAdmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentAttendance> tblStudentAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentDiscipline> tblStudentDisciplines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentMark> tblStudentMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentPayment> tblStudentPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentTutorial> tblStudentTutorials { get; set; }
    }
}
