//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentPayment
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int PaymentReasonID { get; set; }
        public int PaymentPeriodID { get; set; }
        public string RecieptNumber { get; set; }
        public string CashierName { get; set; }
        public string PaidBy { get; set; }
        public bool IsFullyPaid { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblPaymentPeriod tblPaymentPeriod { get; set; }
        public virtual tblPaymentReason tblPaymentReason { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
