//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeachersAttendance
    {
        public int ID { get; set; }
        public int TeachersID { get; set; }
        public int AbsencenceDuration { get; set; }
        public int PermissionTypeID { get; set; }
        public string PermitedBy { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual tblPermissionType tblPermissionType { get; set; }
        public virtual tblTeacher tblTeacher { get; set; }
    }
}
