//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTeacher()
        {
            this.tblGradeCourses = new HashSet<tblGradeCourse>();
            this.tblGradeSections = new HashSet<tblGradeSection>();
            this.tblTeacherEvaluations = new HashSet<tblTeacherEvaluation>();
            this.tblTeachersAttendances = new HashSet<tblTeachersAttendance>();
            this.tblTeacherTutorials = new HashSet<tblTeacherTutorial>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public string MotherName { get; set; }
        public int GenderID { get; set; }
        public int CampusID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FieldOfStudy { get; set; }
        public int DepartmentID { get; set; }
        public int MaritalStatusID { get; set; }
        public int YearOfExperience { get; set; }
        public string SkillDescription { get; set; }
        public int RegionID { get; set; }
        public int SubCityID { get; set; }
        public int WoredaID { get; set; }
        public string HouseNo { get; set; }
        public System.DateTime HiredDate { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblCampu tblCampu { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblGender tblGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGradeCourse> tblGradeCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGradeSection> tblGradeSections { get; set; }
        public virtual tblMaritalStatu tblMaritalStatu { get; set; }
        public virtual tblRegion tblRegion { get; set; }
        public virtual tblSubCity tblSubCity { get; set; }
        public virtual tblWoreda tblWoreda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeacherEvaluation> tblTeacherEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeachersAttendance> tblTeachersAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeacherTutorial> tblTeacherTutorials { get; set; }
    }
}
